spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/first_db?currentSchema=tasklist
    username: postgres
    password: 1488
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: c3ZmYWZzZWduaHNlenNkYXNtdmZrcmVka3NuZmVydmJlam9rc3NrZ21sZnZkd2VmZg==
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false